const units = [
  {title:"מתחילים ממה שמפריע",lead:"לא צריך להגיע עם רעיון לאפליקציה. צריך להגיע עם רגע אחד בהוראה שהיית רוצה שייראה אחרת.",body:`<div class="reflection"><small>שאלה למחשבה</small><p>מה הסטודנטים שלך מפספסים שוב ושוב?</p><textarea class="answer" data-answer="need" placeholder="למשל: הסטודנטים מכירים את הנוסחה, אבל מתקשים לראות מתי נכון להשתמש בה..."></textarea><span class="hint">מספיק משפט אחד. אין צורך לפתור את הבעיה עדיין.</span></div>`},
  {title:"הופכים קושי למטרה",lead:"עכשיו ננסח שינוי קטן שאפשר לזהות. לא “שהסטודנטים יבינו טוב יותר”, אלא מה הם יוכלו לעשות.",body:`<div class="reflection"><small>המשימה שלך</small><p>השלימו: הייתי רוצה שהסטודנטים שלי יוכלו...</p><textarea class="answer" data-answer="goal" placeholder="לזהות, להשוות, לבחור, לתרגל, לראות קשר..."></textarea><span class="hint">בחרו פעולה אחת ממוקדת שאפשר לתרגל או להמחיש.</span></div>`},
  {title:"מתארים את הרעיון ל־AI",lead:"לא צריך לדעת איך לבנות את הכלי. התפקיד שלנו הוא לתאר היטב למי הוא מיועד ומה הוא אמור לאפשר.",body:`<div class="prompt-box"><button class="copy-button" data-copy>העתקה</button><pre>אני מרצה בתחום [התחום שלי].\nהסטודנטים שלי מתקשים ב־[הקושי שזיהיתי].\nאני רוצה כלי קטן שיעזור להם [המטרה שניסחתי].\nהצע רעיון פשוט שאפשר לממש בעמוד HTML אחד.</pre></div><p class="hint">העתיקו את התבנית, השלימו את הפרטים שלכם ושלחו אותה ל־AI.</p>`},
  {title:"עוצרים ומסתכלים",lead:"יש לנו צורך, מטרה ותיאור ראשוני. לפני שעוברים לקוד, נשווה בין הרעיונות ונחדד אותם יחד.",body:`<div class="pause-box"><strong>נקודת עצירה</strong><p>השאירו את החלון פתוח וחזרו לקבוצה.<br>השלב הבא ייפתח בהנחיית המנחה.</p></div>`}
];
let current=Number(localStorage.getItem("workshop-unit")||0);if(current>2)current=0;
const content=document.querySelector("#unit-content"),number=document.querySelector("#unit-number"),prev=document.querySelector("#previous-button"),next=document.querySelector("#next-button");
function render(){const unit=units[current];number.textContent=current+1;content.innerHTML=`<h2>${unit.title}</h2><p class="lead">${unit.lead}</p>${unit.body}`;prev.disabled=current===0;next.disabled=current===3;next.innerHTML=current===2?'הגעתי לנקודת העצירה <span aria-hidden="true">←</span>':current===3?'ממתינים להמשך':'סיימתי, לשלב הבא <span aria-hidden="true">←</span>';document.querySelectorAll(".journey-list li").forEach((li,i)=>li.classList.toggle("active",i===current));document.querySelectorAll(".answer").forEach(el=>{el.value=localStorage.getItem(`answer-${el.dataset.answer}`)||"";el.addEventListener("input",()=>localStorage.setItem(`answer-${el.dataset.answer}`,el.value))});const copy=document.querySelector("[data-copy]");if(copy)copy.addEventListener("click",async()=>{await navigator.clipboard.writeText(copy.nextElementSibling.textContent);copy.textContent="הועתק!";setTimeout(()=>copy.textContent="העתקה",1600)});localStorage.setItem("workshop-unit",current)}
prev.addEventListener("click",()=>{if(current>0){current--;render();document.querySelector(".unit-card").scrollIntoView({behavior:"smooth"})}});next.addEventListener("click",()=>{if(current<3){current++;render();document.querySelector(".unit-card").scrollIntoView({behavior:"smooth"})}});document.querySelectorAll("[data-unit]").forEach(btn=>btn.addEventListener("click",()=>{current=Number(btn.dataset.unit);render()}));document.querySelector("[data-start]").addEventListener("click",()=>document.querySelector(".workspace").scrollIntoView({behavior:"smooth"}));render();
